### ISSUE TITLE
Paytrail-submit event not triggering

### ISSUE THREAD

**Issue by Koura** [paytrail/web-component-e2#12]
**Describe the bug**

Adding a `paytrail-submit` event listener for paytrail-web-component-e2 does not fire and handleSubmit is never called.

**Steps to Reproduce**

1. take the html-example as the base
2. remove all calls to `calculateAuthcode()`
3. add the event listener from [readme example](https://github.com/paytrail/web-component-e2#generating-the-authcode-in-the-back-end)
4. navigate to the browser and press the `pay here` button

**Expected behaviour**

The `handleSubmit` function should be called and paytrail-web-component-e2 doesn't automatically redirect to payment site.

**Actual behaviour**

The `handleSubmit` function is never called and user is automatically redirected to payment site leading to a `invalid authcode` error.

**Comment by Matsuuu** [comment]
Can confirm that this is happening. It's weird how a earlier version of browsers didn't catch this bug.

I'm currently working on a fix to this, but need to spec out a polyfill for safari due to it not supporting [requestSubmit](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit).

Will submit a PR today

**Comment by Matsuuu** [comment]
https://github.com/paytrail/web-component-e2/pull/13 Should get merged soon. @Jipsukka might be able to update you on when it's in npm

**Comment by Matsuuu** [comment]
https://www.npmjs.com/package/@paytrail/web-component-e2 1.0.1 should contain the fix for this.

Thanks @Jipsukka !
