### ISSUE TITLE
The naming convention

### ISSUE THREAD

**Issue by Matsuuu** [paytrail/web-component-e2#8]
The naming convention needs to be decided upon.

In the commit https://github.com/paytrail/web-component-e2/commit/29d06380b5ad168c8c2f99f95e6416f0902592fd , @Jipsukka changed a lot of the naming conventions from the README. 

I'm all fine with the fact that we call it the "web-component-e2" in the GitHub and the npm space, but I feel the when used as a web component, the name should reflect paytrail somehow. 

The (supposedly) find-and-replace change to the naming in the commit above also changed all of the examples so that the web component name doesn't reflect the current state.

### Actionable items

[] Decide which name the Repository has
[] Decide the naming of the web component (I vote for either `<pay-trail>`, `<paytrail-web-component>`  or `<paytrail-web-component-e2>` or of sorts.
[] Release the component after the changes have been made

@Jipsukka Is there any resources available for these actions currently, or in the close by weeks?

**Comment by Jipsukka** [comment]
Problem was that Paytrail was written wrongly. For our own libraries, naming convention is that name should be what library is used, like E2, since that's what matters most, after that comes technology, word Paytrail is already in namespace, so its not needed.
Since this is third party component, it's not that important to follow exactly every rule. Main thing is that it contains information that it's E2 library and it's webcomponent. Also if it has company's name on it, it must be written properly.
So last one you mentioned would be best, if you want to include company name in library name.

**Comment by Matsuuu** [comment]
Yeah that's fully understandable.

I'm going to create a PR in the following days, rewriting the component declaration and class names to reflect the name `<paytrail-web-component-e2>`. Then I'll do a final round of testing and try to check out if there's something new with the API I should consider.

After that I would say we are fairly ready for release

**Comment by Matsuuu** [comment]
@Jipsukka I renamed the component all around and now it should be ready for release
